[run]
allow-parallel-runners = true
timeout = "5m"

[linters]
# Use everything but the style-related linters by default
presets = ["bugs", "comment", "complexity", "error", "format", "import", "metalinter","module",
  "performance", "sql", "style", "test", "unused",]

disable = [
  "wsl", # leave whitespace shaping to personal editor config
  "nlreturn", # leave whitespace shaping to personal editor config
  "varnamelen", # forces long names in short scopes
  "paralleltest", # test runner runs tests in parallel by default
  "forcetypeassert", # covered by errcheck
  "exhaustruct", # structs must be allowed to use default values for terseness
  "depguard", # allow list maintained elsewhere
  "gomodguard", # allow list maintained elsewhere
]

[linters-settings.errcheck]
check-type-assertions = true # should try to avoid panic scenario
check-blank = true # don't ignore errors

[linters-settings.gofumpt]
extra-rules = true # aggressive fumpt

[linters-settings.funlen]
lines = -1 # only count statements, blank lines and comments shouldn't penalize a func

[linters-settings.nolintlint]
require-specific = true
require-explanation = true

# [linters-settings.gci]
# sections = ["standard", "prefix(github.com/janrain/gram)", "default"]
# custom-order = true

[issues]
exclude-use-default = false # skip golang-ci linter omissions
exclude-dirs = ["vendor",] # ignore vendor folder
