---
name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'
      - name: govulncheck
        uses: golang/govulncheck-action@v1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
      - name: make test
        run: make test
